# Generated by Django 2.0.3 on 2018-03-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_idea_challenges'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='linked_ideas',
            field=models.ManyToManyField(related_name='_idea_linked_ideas_+', to='ideas.Idea'),
        ),
    ]
